
services:
  client:
    image: sunilswizy/bitly-client
    container_name: bitly-client
    ports:
      - 80:80
    depends_on:
      - server

  server:
    image: sunilswizy/bitly-server
    container_name: bitly-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local